import Navbar from '@/components/shared/navbar';
import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/providers/auth-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { Analytics } from '@/components/analytics';
import { env } from '@/env';
import { Databuddy } from '@databuddy/sdk/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Databuddy
          clientId={env.NEXT_PUBLIC_DATABUDDY_CLIENT_ID}
          // Core tracking
          trackScreenViews={true}
          trackHashChanges={true}
          trackSessions={true}
          // Interaction tracking
          trackAttributes={true}
          trackOutgoingLinks={true}
          trackInteractions={true}
          // Performance tracking
          trackPerformance={true}
          trackWebVitals={true}
          // Optimization
          enableBatching={true}
          batchSize={10}
          batchTimeout={2000}
          // Development
          disabled={process.env.NODE_ENV !== 'production'}
        />
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <AuthProvider>
            <Navbar />
            {children}
            <Toaster richColors closeButton />
          </AuthProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
